### ISSUE TITLE
some questions about val.py

### ISSUE THREAD

**Issue by yangt1013** [Kevinz-code/CSRA#10]
Thanks for sharing your code,I have som questions about your project. 
 In val.py, the definitionation of follows was empty.
parser.add_argument("--load_from", default="models_local/resnet101_voc07_head1_lam0.1_94.7.pth", type=str)

And I cannot find the saved  model coding about this.
How to use the val.py in your project? and explansion the model saved path clearly?

**Comment by Kevinz-code** [comment]
Hi, @yangt1013 
You can refer to the Validation part in the README file. Specifically, the "resnet101_voc07_head1_lam0.1_94.7.pth" is resnet101 trained with our CSRA(Head=1, lambda=0.1). Download this model from our google drive and validate it.
