### ISSUE TITLE
MobileNet; input size

### ISSUE THREAD

**Issue by sorrowyn** [Kevinz-code/CSRA#6]
Hi kevinz! As far as MobileNet is concerned, what is the input size on different datasets? 
in MS-COCO
in VOC2007
in WIDER
in ImageNet
![图片](https://user-images.githubusercontent.com/19569162/134333943-dbd39909-363b-4a08-bb9b-d31af9ff831d.png)

**Comment by Kevinz-code** [comment]
Hi, @sorrowyn 
Thanks for reading.

Here the the input image size of these datasets:

MS-COCO, VOC2007, VOC2012: 448x448
WIDER Attribute, ImageNet: 224x224

MobileNet in VOC2007: 448x448
MobileNet in WIDER: 224x224
Resolution depends on the dataset instead of the backbone.

Best,
Ke Zhu

**Comment by sorrowyn** [comment]
Thank you for your information, which was very helpful.
